WeBankBlockchain/WeBASE-Front

src/main/java/com/webank/webase/front/base/exception/ExceptionsHandler.java

catch pram exception

---

src/main/java/com/webank/webase/front/Application.java
src/main/java/com/webank/webase/front/base/ConstantCode.java
src/main/java/com/webank/webase/front/base/Constants.java
src/main/java/com/webank/webase/front/keyServer/KeyServerRestTools.java
src/main/java/com/webank/webase/front/keyServer/KeyServerService.java
src/main/java/com/webank/webase/front/keyServer/entity/ReqNewUserDto.java
src/main/java/com/webank/webase/front/keyServer/entity/ReqSignDto.java
src/main/java/com/webank/webase/front/keyServer/entity/RspSignDto.java
src/main/java/com/webank/webase/front/keyServer/entity/RspUserInfoDto.java
src/main/java/com/webank/webase/front/keystore/KeyStoreController.java
src/main/java/com/webank/webase/front/keystore/KeyStoreService.java
src/main/java/com/webank/webase/front/transaction/TransController.java
src/main/java/com/webank/webase/front/transaction/TransService.java
src/main/java/com/webank/webase/front/transaction/entity/ReqTransHandle.java
src/main/java/com/webank/webase/front/util/CommonUtils.java
src/main/resources/application.yml

support webase-sign

---

README.md
interface.md
src/main/java/com/webank/webase/front/contract/ContractController.java

change interface.md、readme.md

---

README.md
interface.md
src/main/resources/application.yml

1、update interface.md
2、Add H2 database description

1、update interface.md

---

src/main/resources/static/config/index.js
src/main/resources/static/src/assets/css/common.css
src/main/resources/static/src/components/metricChart.vue
src/main/resources/static/src/views/index/main.vue
src/main/resources/static/src/views/index/sidebar.vue
src/main/resources/static/src/views/rivateKeyManagement/components/creatUser.vue
src/main/resources/static/src/views/rivateKeyManagement/rivateKeyManagement.vue

update style , createPrivateKey api parame.

update style , createPrivateKey api parame.

---

src/main/resources/static/src/views/rivateKeyManagement/rivateKeyManagement.vue

modify front creat rivateKey api parame

---

src/main/resources/static/src/util/errcode.js
src/main/resources/static/src/views/chaincode/dialog/sendTransaction.vue
src/main/resources/static/src/views/chaincode/oldContract.vue
src/main/resources/static/src/views/index/sidebar.vue
src/main/resources/static/src/views/rivateKeyManagement/rivateKeyManagement.vue

modify icon style, contract abi  'constant = true'

modify icon style, contract abi  'constant = true'

---

src/main/resources/static/build/utils.js
src/main/resources/static/build/webpack.prod.conf.js
src/main/resources/static/src/util/errcode.js
src/main/resources/static/src/views/chaincode/dialog/sendTransaction.vue
src/main/resources/static/src/views/chaincode/oldContract.vue
src/main/resources/static/src/views/index/sidebar.vue
src/main/resources/static/src/views/rivateKeyManagement/rivateKeyManagement.vue

modify  build bug

---

README.md
install_FAQ.md
interface.md
src/main/java/com/webank/webase/front/base/Constants.java
src/main/java/com/webank/webase/front/config/SwaggerConfig.java
src/main/java/com/webank/webase/front/keyServer/KeyServerRestTools.java
src/main/java/com/webank/webase/front/keystore/KeyStoreService.java
src/main/resources/application.yml
src/main/resources/log4j2.xml
src/main/resources/static/config/index.js
src/main/resources/static/src/util/url.js

update: webase-front -> WeBASE-Front
update: webase-node-mgr -> WeBASE-Node-Manager
update: webase-sign -> WeBASE-Sign

update: webase-front -> WeBASE-Front

---

src/main/resources/static/src/views/unusualContract/unusualContract.vue
src/main/resources/static/src/views/unusualUser/unusualUser.vue

modify unusual module css style

modify unusual module css style

---

src/main/java/com/webank/webase/front/base/ConstantCode.java
src/main/java/com/webank/webase/front/contract/ContractController.java
src/main/java/com/webank/webase/front/contract/ContractService.java
src/main/java/com/webank/webase/front/contract/entity/ReqContractCompile.java
src/main/java/com/webank/webase/front/contract/entity/RspContractCompile.java

support compile contract

---

src/main/java/com/webank/webase/front/contract/ContractService.java

throw comtract compile exception

throw compile exception

---

web/src/views/rivateKeyManagement/index.vue

input flie

---

src/main/java/com/webank/webase/front/base/ConstantCode.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigService.java
src/main/resources/application.yml

System Config's db initial added
add sys config tx_gas_limit range
adjust crud remove response

SysConfig init added

---

src/main/java/com/webank/webase/front/keystore/KeyStoreService.java

fix: cache user key of keyServer

fix: cache user key

---

src/main/java/com/webank/webase/front/base/ConstantCode.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledService.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageController.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageService.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigService.java
src/main/java/com/webank/webase/front/util/PrecompiledUtils.java
src/main/resources/application.yml

- add empty list(not null) in PageResponse;
- adjust CRUD response: copy msg in response's data object

Adjust response

---

src/main/java/com/webank/webase/front/base/BasePageResponse.java
src/main/java/com/webank/webase/front/base/BaseResponse.java
src/main/java/com/webank/webase/front/base/ConstantCode.java
src/main/java/com/webank/webase/front/base/RetCode.java
src/main/java/com/webank/webase/front/base/exception/FrontException.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigController.java

- support higher case or lower case
- catch common exception instead of particular exception which not caught
- edit response body "msg" => "message"
- add not paged list of permission list

Fix crud word case

---

.gitignore
web/package.json
web/src/views/chaincode/components/contractCatalog.vue

upgrade vue-json-viewer

---

src/main/java/com/webank/webase/front/base/ConstantCode.java
src/main/java/com/webank/webase/front/base/Constants.java
src/main/java/com/webank/webase/front/cert/FrontCertController.java
src/main/java/com/webank/webase/front/cert/FrontCertService.java
src/main/resources/application.yml

- adjust cert return message;
- update yml constant, replace "nodeCertPath" with "nodePath"

Adjust cert return & update yml constant

---

src/main/java/com/webank/webase/front/cert/FrontCertController.java
src/main/java/com/webank/webase/front/cert/FrontCertService.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/SystemConfigHandle.java
src/test/java/com/webank/webase/front/cert/crtTest.java
src/test/java/com/webank/webase/front/precompiledapi/sysconf/sysConfigDbTest.java

ex: 
read cert file code:  
`
new InputStream(xx) => Files.newInputStream(xx)
`

Add log in Controller & adjust code style

---

src/main/java/com/webank/webase/front/base/AesUtils.java
src/test/java/com/webank/webase/front/keystore/KeyStoreControllerTest.java

fix:Aes encryption policy changed to cbc

fix:Aes encryption policy changed to cbc

---

src/main/java/com/webank/webase/front/base/enums/CertTypes.java
src/main/java/com/webank/webase/front/cert/FrontCertController.java
src/main/java/com/webank/webase/front/cert/FrontCertService.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledService.java
src/main/java/com/webank/webase/front/precompiledapi/precompiledhandle/CnsHandle.java
src/main/java/com/webank/webase/front/precompiledapi/precompiledhandle/ConsensusHandle.java
src/main/java/com/webank/webase/front/precompiledapi/precompiledhandle/CrudHandle.java
src/main/java/com/webank/webase/front/precompiledapi/precompiledhandle/NodeInfo.java
src/test/java/com/webank/webase/front/cert/NodeCrtTest.java
src/test/java/com/webank/webase/front/cert/SdkCertTest.java

- add sdk.crt for nodemgr
- change precompiled package name
- fix bug in FrontCertController

Add sdk.crt in cert module

---

web/package.json
web/src/util/SM2Sign.js
web/src/util/api.js
web/src/util/ethAbi.js
web/src/util/sm_sha.js
web/src/util/sm_sm3.js
web/src/util/sm_utils.js
web/src/views/chaincode/components/code.vue
web/src/views/rivateKeyManagement/index.vue

support sm encryption

---

src/main/java/com/webank/webase/front/transaction/TransService.java
src/main/java/com/webank/webase/front/transaction/entity/ContractFunction.java
src/main/java/com/webank/webase/front/transaction/entity/ContractOfTrans.java
src/main/java/com/webank/webase/front/transaction/entity/ReqTransHandle.java
src/main/java/com/webank/webase/front/util/ContractAbiUtil.java

Support sending transactions based on contract abi

change method of transaction: Support sending transactions based on contract abi

---

src/main/java/com/webank/webase/front/base/code/ConstantCode.java
src/main/java/com/webank/webase/front/contract/ContractController.java
src/main/java/com/webank/webase/front/contract/ContractService.java
src/main/java/com/webank/webase/front/contract/entity/ReqContractCompile.java
src/main/java/com/webank/webase/front/contract/entity/ReqDeploy.java
src/main/java/com/webank/webase/front/contract/entity/ReqDeployWithSign.java
src/main/java/com/webank/webase/front/contract/entity/RspContractCompile.java
src/main/java/com/webank/webase/front/monitor/MonitorController.java
src/main/java/com/webank/webase/front/monitor/MonitorService.java
src/main/java/com/webank/webase/front/monitor/entity/GroupSizeInfo.java
src/main/java/com/webank/webase/front/util/CommonUtils.java

add interfaces: 
checkNodeProcess
getGroupSizeInfos
optimize:
contractBin change to bytecodeBin

add interfaces

---

src/main/java/com/webank/webase/front/base/code/ConstantCode.java
src/main/java/com/webank/webase/front/event/EventController.java
src/main/java/com/webank/webase/front/event/EventService.java
src/main/java/com/webank/webase/front/event/entity/ReqContractEventRegister.java
src/test/java/com/webank/webase/front/event/EventControllerTest.java

add validation & update abi to list & optimize registerService

---

src/main/java/com/webank/webase/front/base/config/NodeConfig.java
src/main/java/com/webank/webase/front/base/properties/Constants.java
src/main/java/com/webank/webase/front/logparse/LogParseService.java
src/main/java/com/webank/webase/front/logparse/entity/NetWorkData.java
src/main/java/com/webank/webase/front/logparse/entity/TxGasData.java
src/main/java/com/webank/webase/front/logparse/util/FileUtil.java
src/main/java/com/webank/webase/front/monitor/MonitorService.java
src/main/java/com/webank/webase/front/util/CommonUtils.java

optimize: 
1. groupDataPath get from config.ini
2. check stat log files

optimize: groupDataPath get from config.ini

---

build.gradle
src/main/java/com/webank/webase/front/base/code/ConstantCode.java
src/main/java/com/webank/webase/front/event/ContractEventInfoRepository.java
src/main/java/com/webank/webase/front/event/EventService.java
src/main/java/com/webank/webase/front/event/MQService.java
src/main/java/com/webank/webase/front/event/NewBlockEventInfoRepository.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledService.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigController.java
src/main/java/com/webank/webase/front/transaction/TransService.java
src/main/java/com/webank/webase/front/transaction/entity/ContractOfTrans.java
src/main/java/com/webank/webase/front/util/RabbitMQUtils.java
src/main/java/com/webank/webase/front/web3api/Web3ApiService.java
src/main/resources/application.yml

- precompiled useAes default true 
- catch web3jService nullpointer/out of arry boundary exception
- fix funcParam check in transaction
- update blockEvent concurrent and add register try-catch
- update h2 path from `./h2` to `../h2`

Bugfix precompiled useAes default true & web3j exception & register try catch

---

Changelog.md
build.gradle
src/main/java/com/webank/webase/front/base/code/ConstantCode.java
src/main/java/com/webank/webase/front/event/ContractEventInfoRepository.java
src/main/java/com/webank/webase/front/event/EventService.java
src/main/java/com/webank/webase/front/event/MQService.java
src/main/java/com/webank/webase/front/event/NewBlockEventInfoRepository.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledController.java
src/main/java/com/webank/webase/front/precompiledapi/PrecompiledService.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageController.java
src/main/java/com/webank/webase/front/precompiledapi/permission/PermissionManageService.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigController.java
src/main/java/com/webank/webase/front/precompiledapi/sysconf/PrecompiledSysConfigService.java
src/main/java/com/webank/webase/front/transaction/TransService.java
src/main/java/com/webank/webase/front/transaction/entity/ContractOfTrans.java
src/main/java/com/webank/webase/front/util/RabbitMQUtils.java
src/main/java/com/webank/webase/front/web3api/Web3ApiService.java
src/main/resources/application.yml
start.sh
status.sh
stop.sh

- fix precompiled api useAes default value
- fix web3jMap nullpointer & out of boundary error
- upgrade fastjson v1.2.67
- optimize event module's consistency problem, update map to concurrent and add try-catch

v1.2.4 bugfix

---

build.gradle
src/main/java/com/webank/webase/front/util/ContractTypeUtil.java

1、update web3sdk to 2.4.0
2、bugfix bytes encode and decode

update web3sdk and bugfix

---

Changelog.md
build.gradle

update sdk to 2.5.1

---

src/main/resources/static/index.html
web/config/index.js

update static file

---

web/src/views/chaincode/components/contractCatalog.vue
web/src/views/chaincode/contract.vue
web/src/views/index/main.vue

check solc version bug

---

web/src/views/chaincode/contract.vue

 downloading solc.js add 'loading'

---

web/index.html
web/src/views/chaincode/components/contractCatalog.vue

Contract upload optimization

---

src/main/java/com/webank/webase/front/transaction/TransService.java

1、修改TransService，支持在constant关键字下可以使用msg.sender对合约进行调用；
2、页面没有修改，所以constant等关键字合约调用保持不变；

Fix view msgsender

---

src/main/java/com/webank/webase/front/tool/ToolController.java

 Task: 新增16进制私钥转10进制私钥的tool接口

---

web/src/components/sendTransaction.vue

不太懂前端，只改了正则部分。
这个bug对于开发还是有一定影响的，或许可以尽快发新版。

Task 修复交易窗口正则，fix [#744]

---

web/src/components/sendTransaction.vue

校验int/uint/uint256参数格式的正则表达式（当前错误代码为1-9），支持输入参数为0，即支持0-9的数字

webase task5: 校验int/uint/uint256参数格式的正则表达式

---

web/src/lang/en.js
web/src/lang/zh.js

在原有提示语基础上，添加Struct 和 Tuple类型入参的中、英文提示语。测试如图：

WeBASE Task 2: struct Tuple类型入参增加提示语

---

src/main/java/com/webank/webase/front/precompiledapi/crud/CRUDParseUtils.java

支持如下SQL :
```SQL
create table t_demo(`name` varchar, `item_id` varchar, `group` varchar, primary key(`name`))
insert into t_demo (`name`, `item_id`,  `group`) values (book, 1, 1)
select `name`, `item_id`,  `group` from t_demo where `name` = book
update t_demo set `group` = book where `name` = book
delete from t_demo where `name` = book
```

webase 界面新增列名转义兼容 

---

工具合约-Crypto合约详细使用.md

[工具合约-Crypto合约详细使用.md](https://github.com/WeBankBlockchain/WeBASE-Front/files/11403779/-Crypto.md)

TASK1 工具合约-SmartDevBasic仓库-Crypto合约使用

---

src/main/java/com/webank/webase/front/base/config/NodeReqInterceptor.java
src/main/java/com/webank/webase/front/base/config/WebMvcConfig.java
src/main/java/com/webank/webase/front/base/properties/Constants.java
src/main/java/com/webank/webase/front/event/callback/SyncEventLogCallback.java
src/main/java/com/webank/webase/front/keystore/KeyStoreService.java
src/main/java/com/webank/webase/front/precntauth/authmanager/committee/CommitteeController.java
src/main/java/com/webank/webase/front/precntauth/authmanager/committee/CommitteeService.java
src/main/java/com/webank/webase/front/precntauth/authmanager/util/AuthManagerService.java
src/main/java/com/webank/webase/front/precntauth/precompiled/consensus/ConsensusController.java
src/main/java/com/webank/webase/front/precntauth/precompiled/consensus/ConsensusServiceInWebase.java
src/main/java/com/webank/webase/front/util/CommonUtils.java
src/main/java/com/webank/webase/front/util/PrecompiledUtils.java
src/main/java/com/webank/webase/front/version/VersionService.java
src/main/resources/log4j2.xml

1、支持创建链的时候设置开启权限的相关处理，增加修改节点状态进行提案等实现
2、集成微服务架构后，调用sign相关的url适配

Lab 3.0 microservice for front modify
